config/routes.rb
Rails.application.routes.draw do
  root 'chat#index'

  post '/chat/user-sign-in', to: 'chat#user_sign_in', as: 'user_sign_in'
  get '/chat/:user', to: 'chat#user_home', as: 'user_home'

  post '/chat/channel-sign-in', to: 'chat#channel_sign_in', as: 'channel_sign_in'
  get '/chat/:channel/:user', to: 'chat#channel', as: 'channel'


  resources :users
  resources :messages
  resources :channels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
	has_many :messages, dependent: :destroy
  has_many :users, through: :messages

	def self.users(channel)
		Channel.find_by(name: channel).messages.collect { |m| m.user.name }.uniq
	end
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :channel

	before_create :set_time


	private

	def set_time
		self.date = Time.now
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :messages
  has_many :channels, through: :messages

	before_create :get_color

	def self.colors
		User.all.collect { |u| u.color }
	end

	private

	def get_color
    color = '#%06x' % (rand * 0xffffff)
    min_color_num = color.scan(/\d/).map(&:to_i).min || 0

    while ( User.colors.include?(color) ||  min_color_num < 5 ) do
      color = '#%06x' % (rand * 0xffffff)
      min_color_num = color.scan(/\d/).map(&:to_i).min || 0
      puts min_color_num
    end

    self.color = color
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  before_action :set_user, only: [:user_sign_in, :user_home]
  before_action :setup_channel, only: [:channel_sign_in, :channel]

# User Can Sign In
  def index
    @users = User.all
  end

# Signs in
  def user_sign_in
    session[:current_user] = @user.id

    redirect_to user_home_path(@user)
  end

# Enters Channel Selection
  def user_home
    @channels = Channel.all
  end

# Signs in to channel
  def channel_sign_in
    Message.create message: "#{@user.name} HAS ENTERED THE CHANNEL!",
                    user_id: User.first.id,
                    channel_id: @channel.id

    redirect_to channel_path(@channel, @user)
  end

# Enters Channel
  def channel
    @channels = Channel.all
    @message = Message.new
  end

  private

  def set_user
    @user = User.find(params[:user])
  end

  def setup_channel
    @channel = Channel.find(params[:channel])
    @user = User.find(session[:current_user])
    @messages = @channel.messages.sort_by &:date
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to channel_path(@message.channel, @message.user), notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:date, :message, :user_id, :channel_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    # render json: @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/channels/_form.html.erb
<%= form_for(channel) do |f| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message Count</th>
      <th>User Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.name %></td>
        <td><%= channel.messages.count %> </td>
        <td><%= Channel.users(channel.name).count %> </td>
        <td><%= link_to "Chat", chat_path(channel, channel.users.first)%></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>

app/views/chat/channel.html.erb
<h3>Hi <%= @user.name %>, you are in the channel: <%= @channel.name %></h3>
<form action='/chat/channel-sign-in', method='post'>
  <input type="hidden" name="authenticity_token" value="token_value">
  <label for="channel">CHANNELS: </label>
  <select name="channel" id="channel">
    <% @channels.each do |c| %>
      <option value=<%= c.id %>><%= c.name %></option>
    <% end %>
  </select>
  <input type="submit" value="Switch Chat">
</form>

<p>Message Count: <%= @messages.count %></p>
<ul id="chat-window">
  <% @messages.each do |m| %>
    <li class="chat-message" style="background-color: <%= m.user.color %>"><%= m.date %> | <%= m.user.name %>: <%= m.message %></li>
    <% end %>
</ul>

<hr>

<div class="message-form">
  <%= form_for(@message) do |f| %>
    <% if @message.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

        <ul>
        <% @message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :message %>
    <%= f.text_field :message %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.hidden_field :channel_id, value: @channel.id %>
    <%= f.submit %>
  <% end %>
</div>

<script>
  $("#chat-window").animate({ scrollTop: $("#chat-window")[0].scrollHeight }, "fast");

  $("#message_message").focus();
  $("#message_message").select();
</script>

app/views/chat/chat.html.erb
<h1>Welcome to <%= @channel.name %></h1>

<p>Message Count: <%= @messages.count %></p>
<ul id="chat-window">
  <% @messages.each do |m| %>
    <li class="chat-message" style="background-color: <%= m.user.color %>"><%= m.date %> | <%= m.user.name %>: <%= m.message %></li>
    <% end %>
</ul>

<hr>

<div class="message-form">
  <%= form_for(@message) do |f| %>
    <% if @message.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

        <ul>
        <% @message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :message %>
    <%= f.text_field :message %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.hidden_field :channel_id, value: @channel.id %>
    <%= f.submit %>
  <% end %>
</div>


<script>
  $("#chat-window").animate({ scrollTop: $("#chat-window")[0].scrollHeight }, "fast");

  $("#message_message").focus();
  $("#message_message").select();
</script>

app/views/chat/index.html.erb
<h3>Select a User to sign in.</h3>
<form action='/chat/user-sign-in', method='post'>
  <input type="hidden" name="authenticity_token" value="token_value">
  <label for="user">USER: </label>
  <select name="user" id="user">
    <% @users.each do |u| %>
      <option value=<%= u.id %>><%= u.name %></option>
    <% end %>
  </select>

  <input type="submit" value="Enter">
</form>

app/views/chat/user_home.html.erb
<h3 style="background-color: <%= @user.color %>">Hello <%= @user.name %>, Select a Channel to join.</h3>

<form action='/chat/channel-sign-in', method='post'>
  <input type="hidden" name="authenticity_token" value="token_value">
  <label for="channel">CHANNELS: </label>
  <select name="channel" id="channel">
    <% @channels.each do |c| %>
      <option value=<%= c.id %>><%= c.name %></option>
    <% end %>
  </select>
  <input type="submit" value="Enter Channel">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatAppRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Welcome to Chap App - Rails Version</h1>
    <nav>
      <div><%= link_to "Home", root_path %>|<%= link_to "Users", users_path %>|<%= link_to "Channels", channels_path %>|<%= link_to "Messages", messages_path %></div>
    </nav>
    <hr>
      <%= yield %>
    <hr>
    <footer>
        Website Footer.
    </footer>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :channel_id %>
    <%= f.number_field :channel_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Message</th>
      <th>User</th>
      <th>Channel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.date %></td>
        <td><%= message.message %></td>
        <td style="background-color: <%= message.user.color %>"><%= message.user.name %></td>
        <td><%= message.channel.name %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @message.date %>
</p>

<p>
  <strong>Message:</strong>
  <%= @message.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @message.channel_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td style="background-color: <%= user.color %>"><%= user.color %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @user.color %>
</p>

<ul class="channels">
  <% @user.channels.each do |c| %>
    <li><%= c.name %></li>
  <% end %>
</ul>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>